# Generated by Django 5.0.6 on 2024-07-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='orgId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
    ]
