# Generated by Django 5.0.6 on 2024-07-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_organisation_orgid_remove_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='orgId',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userId',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
