# Generated by Django 5.0.6 on 2024-07-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='orgId',
            field=models.CharField(default=1, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(default=1, max_length=255, unique=True),
        ),
    ]
