# Generated by Django 5.0.6 on 2024-07-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='id',
            new_name='orgId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='userId',
        ),
    ]
